### PR TITLE
updates to two pop results

### PR DESCRIPTION
**Pull request by ckyriazis**
I made some revisions to the two population results section. I also added in the figure captions for the generic IM results and migration rates figures in the SI and changed some pngs to pdfs.

### CODE REVIEW

**Comment by andrewkern** [comment]
@ckyriazis looks like some conflicts crept in. Can you try to sort these out on your end?

**Comment by ckyriazis** [comment]
Done.

**Comment by andrewkern** [comment]
wait something bad just happened there. Can you try to rebase against upstream master?

**Comment by ckyriazis** [comment]
Ok i just rebased. Did that fix it?

**Comment by andrewkern** [comment]
yeah-- rebase is better than merge in these cases

**Review by andrewkern — APPROVED** [review]

**Pull request merged**
