### PR TITLE
added text about pop-size scaling

### PR DESCRIPTION
**Pull request by jradrion**
I drafted a little section about population-size rescaling. Feel free to revise as needed.

...also noticed that at least some of our citations were not up to date, though I only updated the one. I'll make a new issue about this.

### CODE REVIEW

**Comment by petrelharp** [comment]
Thanks! We need some citations for "rescaling" and some careful words about how it's *not* equivalent - the docs can provide guidance for both.  Do you want to draft that?

**Comment by jradrion** [comment]
> Thanks! We need some citations for "rescaling" and some careful words about how it's not equivalent - the docs can provide guidance for both. Do you want to draft that?

Sure, I just didn't know what the appropriate citation would be exactly? The SLiM manual states, "For further discussion of model rescaling, Uricchio & Hernandez (2014) may be of interest, and citations therein". Can you confirm that Uricchio & Hernandez (2014) is the proper citation for rescaling as implemented in SLiM? The phrase "may be of interest" doesn't explictly imply that their method was used. I don't know this literature, so I feel somewhat uncomfortable providing a citation for how someone else handled population rescaling in their software.

**Comment by petrelharp** [comment]
That is a good citation, but see the stdpopsim docs also.

>

**Comment by jradrion** [comment]
alright, let me know what you think of these changes

**Comment by petrelharp** [comment]
Thanks! I'll merge this; we can continue to edit it along with everything else.

**Pull request merged**
