### PR TITLE
adam + dan comments in a clean PR

### PR DESCRIPTION
**Pull request by andrewkern**
Adam's PR had some conflicts so I pulled out his edits to a new PR. Along the way @dschride had comments that I tried to incorporate here. 

This is a rather large overhaul of the discussion which I quite like a lot. I'd like others to approve it though before a merge.

### CODE REVIEW

**Review by dschride — APPROVED** [review]
No more changes from me.

**Review by petrelharp — COMMENTED** [review]
This is an improvement; I say merge this.

**Comment by petrelharp** [comment]
My only suggestion is that we upweight the goal of reducing the barrier to using complex simulations, since (I think?) that may well be the long-run most influential aspect of all this. It's mentioned in the third paragraph, but this could be included in one of the "goals" of the first paragraph, and perhaps discussed with another sentence in the third paragraph.

**Comment by andrewkern** [comment]
want to take a stab at it?

**Comment by petrelharp** [comment]
see https://github.com/andrewkern/manuscript/pull/1

**Pull request merged**
