### PR TITLE
Small edits about how we refer to populations, simulated populations, and samples from populations

### PR DESCRIPTION
**Pull request by sgravel**
Small language fix -- We shouldn't say that the YRI population history is simple :)

### CODE REVIEW

**Comment by andrewkern** [comment]
looks good. can you rebase to squash these to a single commit and I'll merge?

**Comment by andrewkern** [comment]
btw the commit history looks weird here. you will want to do the following:

```
git fetch upstream
git rebase -i upstream/master
git push -f origin feature_branch_name
```

**Comment by andrewkern** [comment]
i'm going to close down this PR as it is mangled in its commit history. @jradrion did you mean to push to this PR? @sgravel can you please put these edits in a new, clean PR? 

thanks!

**Comment by jradrion** [comment]
lol, no. not sure how that happened

my apologies!

**Pull request closed without merging**
