### PR TITLE
Initial benchmarks for simulations

### PR DESCRIPTION
**Pull request by jeromekelleher**
Here's an initial pass at running benchmarks for the simulations. Specifically, I ran 100 samples from population zero, for each of the models, using the shortest chromosome. There's a million other things we could do, but this gives some idea of the amount of time and space involved. Basically they're all pretty fast and don't use much RAM, although there are notable differences between the human models that I'm not sure I understand.

We can tidy up the table when the various names have been finalised.

Screenshot from 2019-12-05 10-37-34

### CODE REVIEW

**Comment by jeromekelleher** [comment]
OK, squashed the commits and merging.

**Comment by agladstein** [comment]
> 100 samples from population zero

I don't understand what you mean here. If there are more than one population, how many samples did you simulate?

I'd probably prefer to see it with the longest chromosome... or maybe shortest and longest.
Are these run with genetic maps?

**Comment by jeromekelleher** [comment]
> I don't understand what you mean here. If there are more than one population, how many samples did you simulate?

I just took 100 samples from the first population, in every case. Genetic material will end up in the other populations via migration, so it's not that different to taking samples in all of them, and it's a lot simpler.

> I'd probably prefer to see it with the longest chromosome... or maybe shortest and longest.
Are these run with genetic maps?

Yeah, there's an argument for doing the longest chromosome all right. They're not done with genetic maps, no, this is the simplest case. I don't see much point in burning a lot of electricity on this, tbh, we're not trying to compare with anything else, we just want to give a rough indication of how long stuff takes.

**Comment by dschride** [comment]
RE: sampling 100 chromosomes from pop zero: I get what you are trying to do in going for an apples-to-apples comparison, but I kind of feel that this is actually doing the opposite by giving overoptimistic assessments of some of the multipop scenarios? Anyway I agree that you shouldn't be sinking too much time into this so I'm fine either way.

**Comment by agladstein** [comment]
> I just took 100 samples from the first population, in every case

I see.

I would think it's more likely that people would be using the genetics map. So, I think it'd be helpful to do it with a genetic map. But, also, I don't think it's super important.

**Pull request merged**
