### PR TITLE
Rough outline for catalog table.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Here's a rough draft of what the catalog table might look like for comments.
Screenshot from 2019-11-26 20-32-45

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thoughts:
- We definitely need better IDs for the population models. There must be some reasonably systematic way we can come up with decent IDs.
- The Kamm model needs work.

With that, we should be able to get these 5 columns in and prettyify the presentation a bit. What do we think?

**Comment by andrewkern** [comment]
looks great to me as a rough mock up.

I agree we need better model IDs and perhaps a controlled naming convention. Would it be enough to track the population labels and the first author? Like YRI_CEU_CHB_Gutenkunst?

**Comment by andrewkern** [comment]
btw I see in this PR that you are editing the original manuscript file-- we should coordinate merging this with my PR somehow.

**Comment by jeromekelleher** [comment]
> btw I see in this PR that you are editing the original manuscript file-- we should coordinate merging this with my PR somehow.

Sure --- the changes are minimal to get the table in and make the latex compile. It'll be an easy merge. I'd suggest getting your changes merged first and I'll port this in afterwards.

**Comment by jeromekelleher** [comment]
> I agree we need better model IDs and perhaps a controlled naming convention. Would it be enough to track the population labels and the first author? Like YRI_CEU_CHB_Gutenkunst?

That's a pretty long thing to be typing out. We want something that 6-9 characters, ideally.

**Comment by jeromekelleher** [comment]
See https://github.com/popgensims/stdpopsim/issues/122 and https://github.com/popgensims/stdpopsim/issues/123 for issues discussing the ID scheme problems.

**Comment by andrewkern** [comment]
wondering if we should even mention E. coli in the paper? we have very little implemented for it right now

**Comment by jeromekelleher** [comment]
Yeah, worth thinking about all right. Three is a good number of species to implement.

**Comment by andrewkern** [comment]
@jeromekelleher can you resolve these conflicts, rebase, and then we can merge this in?

**Comment by jeromekelleher** [comment]
Fixed up and merging. I'll follow up with some simulation timing data and tidyup.

**Pull request merged**
