### PR TITLE
minor adjustment

### PR DESCRIPTION
**Pull request by petrelharp**
I've reworded the bit that @andrewkern pointed out did not read well, and added a note that the OOA whoopsie was used in other (unnamed) papers, to help alert people (how's it sound, @jeromekelleher?).

### CODE REVIEW

**Comment by petrelharp** [comment]
Also doing as @gphocs-dev says:
> We should remove the  \paragraph{The \stdpopsim library.} title in the beginning of the results section, and maybe also mention the use case of demographic inference comparison in this short intro paragraph (although I'm not sure that's necessary).

I'm also changing "species" to "taxa" in that introductory sentence?

**Comment by gphocs-dev** [comment]
I would vote for "species" here, even if our classes don't always accurately associate with species.

**Comment by petrelharp** [comment]
> I would vote for "species" here, even if our classes don't always accurately associate with species.

Sure, I guess "growing list of species" still works, since it's not saying there's a 1-to-1 correspondence of species to rows in the table.

**Comment by petrelharp** [comment]
These commits are now in #192, so I'll close this.

**Pull request closed without merging**
