### PR TITLE
updated figure S4

### PR DESCRIPTION
**Pull request by jradrion**
Here are the updated n_t results and resulting figure for the QC'd OutOfAfrica_3G09

### CODE REVIEW

**Comment by petrelharp** [comment]
Awesome!

@asiepel asks in a comment in the manuscript about this figure:
```
% ACS: do we need the "Homo sapiens" at top left in the figure?  It breaks the visual symmetry among YRI, CEU, and CHB, and 
% I think it is unnecessary given the population labels and the description in the legend
% Also: should we include "N(t)" after "Population size" in the y-axis label, to drive home its meaning (used in the text and legend)?
```

These seem like good suggestions; could you update the figure or respond?

**Comment by petrelharp** [comment]
Here's the comparison: old figure on the right; new on the left. Looks pretty similar overall: any differences of note?
Screenshot from 2020-05-05 20-28-57

**Comment by andrewkern** [comment]
agreed these look very similar to my eye

**Comment by jeromekelleher** [comment]
Seems like there's a few qualitative differences to me? e.g. MSMS-CHB looks have a much larger estimate in the recent past?

**Comment by jradrion** [comment]
@petrelharp @asiepel 
> % ACS: do we need the "Homo sapiens" at top left in the figure?  It breaks the visual symmetry among YRI, CEU, and CHB, and 
> % I think it is unnecessary given the population labels and the description in the legend
> % Also: should we include "N(t)" after "Population size" in the y-axis label, to drive home its meaning (used in the text and legend)?

> These seem like good suggestions; could you update the figure or respond?

I agree that the species label does somewhat detract from the symmetry, but we should also then remove this label from all similar figures (Figures 2,3,4,S3,S4,S5,S6,S8) for consistency, no? I'll need to modify them to add "N(t)" regardless.

@ckyriazis can you make these changes to your figs as well?

**Comment by ckyriazis** [comment]
sure, no problem! should I add "N(t)" to the y axis label as well?

**Comment by jradrion** [comment]
> sure, no problem! should I add "N(t)" to the y axis label as well?

Yeah, I think that would probably be best

**Comment by jradrion** [comment]
The updated figure types (3-,4-,and 12-panel) are shown below:
HomSap_OutOfAfricaArchaicAdmixture_5R19_census_vs_IRC
AraTha_African2Epoch_1H18
HomSap_OutOfAfrica_3G09

**Comment by petrelharp** [comment]
Thanks! I'll merge this now, since the new words will come in via #193, I think?

**Pull request merged**
