### PR TITLE
minor edits -- typos, grammar, clarity

### PR DESCRIPTION
**Pull request by asiepel**

### CODE REVIEW

**Comment by petrelharp** [comment]
LMK when you are done and I'll reconcile #127 with your changes here (unless someone else wants to).

**Comment by asiepel** [comment]
Done

Adam
Sent from my iPhone

On Dec 20, 2019, at 11:36 AM, Peter Ralph <notifications@github.com> wrote:

﻿

LMK when you are done and I'll reconcile #127<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_popsim-2Dconsortium_manuscript_pull_127&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=rNAqNCgksGfltoLkih1npA&m=2h5HTkNc0ft1t1w5btwdh6P2fYxlCFwMxtEyAHRQJFs&s=6rQ0eE938VpBnyevOqgS_co0Iix8EiEIn7NaoteMWlQ&e=> with your changes here (unless someone else wants to).

**Comment by petrelharp** [comment]
LGTM!

**Review by andrewkern — APPROVED** [review]
lgtm

**Comment by andrewkern** [comment]
so @petrelharp do you want me to merge this before we merge https://github.com/popsim-consortium/manuscript/pull/127 ?

**Comment by petrelharp** [comment]
> so @petrelharp do you want me to merge this before we merge #127 ?

yep

**Pull request merged**
