### PR TITLE
Response to request for dynamic catalog.

### PR DESCRIPTION
**Pull request by jeromekelleher**
I've basically said, "great idea but we can't do it now". The reviewer does ask us to flag this as something for future development, but I'm not sure where. Perhaps we should add another subsection in the methods call "Model lifecycle" or something, in which we could address this along with the major points they are making in point 1? So, something like

## Model lifecycle

All entries in the catalog represent best estimates of parameter values at the time of publication and are subject to change over time. [Talk about genome builds etc.] As the selection of models grows, we hope to develop an improved documentation system that will incorporate crowd sourced community input to help new users find the most appropriate models quickly.

Or, I guess we could put this in as a paragraph in the discussion?

### CODE REVIEW

**Comment by petrelharp** [comment]
You could just open a github issue and point the reviewer to it?

**Comment by jeromekelleher** [comment]
We still need to address the point about best estimates and stuff in the manuscript though, so including this (good) idea in there seems natural. Question is, where?

**Comment by petrelharp** [comment]
This does seem like an item for the Discussion.

**Comment by andrewkern** [comment]
> All entries in the catalog represent best estimates of parameter values at the time of publication and are subject to change over time. [Talk about genome builds etc.] As the selection of models grows, we hope to develop an improved documentation system that will incorporate crowd sourced community input to help new users find the most appropriate models quickly.

I think we could add two to three sentences along these lines [here](https://github.com/popsim-consortium/manuscript/blob/6359247e3b7b32618c4a87856b6a54afe3205bb8/popSimManu.tex#L640)

@jeromekelleher do you want to have a stab here and then we can merge?

**Comment by jeromekelleher** [comment]
Good call @andrewkern, I'll make a pass at it.

**Comment by jeromekelleher** [comment]
I'll wait until #158 is merged before editing, save us a merge collision.

**Comment by petrelharp** [comment]
Could you see if this is said in the current Response and if not then rebase or something? Don't know how I missed this earlier; sorry.

**Comment by jeromekelleher** [comment]
I messed up the gitting, was easier to make a new pr with the updates. See #182

**Pull request closed without merging**
