### PR TITLE
updated two pop figures and src

### PR DESCRIPTION
**Pull request by ckyriazis**
I reran the two population analysis with the fixed Gutenkunst model and made modifications to all the two pop figures following @jradrion's changes. The results are essentially the same for dadi and fsc though appear to be much better for SMC++. 

I also had to update SMC++ from 1.13.1 to 1.15.2 to deal with some compatibility issues so its possible (though I think unlikely) there were performance improvements in those updates that could also be impacting the new results. 

In any case, we may need to tweak the language we use in the manuscript to describe these results because they do look quite good (before they were a bit noisier).

### CODE REVIEW

**Comment by jradrion** [comment]
Great! I'm seeing similar results on the n_t side. I'm rerunning some simulations to double check changes I made to the snakefile, but I should be able to post updated figs in a PR later today.

**Comment by petrelharp** [comment]
Great! Would you like to also have a go at modifying the language?

**Comment by jradrion** [comment]
> Great! Would you like to also have a go at modifying the language?

@petrelharp was this comment directed at me or @ckyriazis ?

I'm happy to make edits or to let @ckyriazis do it; I'm just trying to avoid both of us working on the same section simultaneously.

**Comment by ckyriazis** [comment]
i can take care of this!

**Comment by ckyriazis** [comment]
just made some more minor modifications to the figures and a few tweaks to the ms where we interpret the two pop results to reflect the improved performance of smc++. i wasnt sure if there were any needed changes for the single pop results interpretation since they did not change much? if you see any places let me know and i can do some tweaking.

**Comment by petrelharp** [comment]
Is it easy for you to post a before-and-after of the figs?

**Comment by ckyriazis** [comment]
yea! left is before, right is after. 
Screen Shot 2020-05-07 at 11 13 53 AM

**Comment by petrelharp** [comment]
Looks good to me! Thanks a bunch.

It's pretty nice how smc++ improves here.

**Comment by ckyriazis** [comment]
Agreed! I'm impressed at how well it does with the CEU pop size.

**Comment by petrelharp** [comment]
Ok! I will merge this.

**Pull request merged**
