### PR TITLE
asiepel edits

### PR DESCRIPTION
**Pull request by asiepel**

### CODE REVIEW

**Comment by petrelharp** [comment]
Gee, thanks for pulling in my tweaks, even. Let us know when you're ready for us to look at this?

**Comment by asiepel** [comment]
I just pushed some more tweaks through the Results section.  I’m still hoping to take a pass on the Discussion, but I’ll have to come back to that later this afternoon.  You could review the pull request in the meantime if you have a chance.
Adam

**Comment by asiepel** [comment]
I made a few very minor edits to the discussion and am done for now.  All in PR #192

**Comment by petrelharp** [comment]
This looks great. I'm doing a scan through the diff to look for errors that have been introduced in the last round of edits, and have some minor follow-up adjustments that I'll put in a separate PR.

**Pull request merged**
