### PR TITLE
some reworking of Discussion

### PR DESCRIPTION
**Pull request by asiepel**
Reworking of second half of discussion

### CODE REVIEW

**Comment by andrewkern** [comment]
these edits look really good to me Adam. Before I go through the trouble of manually resolving the conflicts. I'd like to get other eyes on it. what do others think @petrelharp @dschride @jeromekelleher

**Comment by asiepel** [comment]
Yes sorry for the trouble.

Sent from my iPad

On Dec 18, 2019, at 5:50 PM, Andrew Kern <notifications@github.com<mailto:notifications@github.com>> wrote:


these edits look really good to me Adam. Before I go through the trouble of manually resolving the conflicts. I'd like to get other eyes on it. what do others think @petrelharp<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petrelharp&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=rNAqNCgksGfltoLkih1npA&m=MpsM9O00apSwVjvpQnwztDTA0VajlkKOcKkV56Z655g&s=pTS2BrJ3ujKTHgM-Y1XRu4WU7N1AU7Bc-NdnUXxuSEU&e=> @dschride<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dschride&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=rNAqNCgksGfltoLkih1npA&m=MpsM9O00apSwVjvpQnwztDTA0VajlkKOcKkV56Z655g&s=UrAPg3QQ7Io-SKGuwny0Lgsw4iwwhIokdQGikaJCZDI&e=> @jeromekelleher<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jeromekelleher&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=rNAqNCgksGfltoLkih1npA&m=MpsM9O00apSwVjvpQnwztDTA0VajlkKOcKkV56Z655g&s=KxiNjW0cqO9-4jD4_dSxB41DshV7WnVaWhBcwzg-JyY&e=>

**Comment by dschride** [comment]
I like the reorganization here. Sent a few comments to Andy about making a couple of minor tweaks but I think its definitely coming together!

**Comment by andrewkern** [comment]
I'm going to pull together these edits from Adam and the ones from Dan into a new PR

**Comment by andrewkern** [comment]
closing this as I moved these edits to https://github.com/popsim-consortium/manuscript/pull/80

**Pull request closed without merging**
