### PR TITLE
KEL edits on abstract & intro

### PR DESCRIPTION
**Pull request by klohmueller**
Here's my first pass on Abstract & intro of ms

### CODE REVIEW

**Comment by andrewkern** [comment]
@klohmueller looks like there are some major issues with your PR here-- it looks like you were editing a version without any of the up to date merges maybe?

**Comment by andrewkern** [comment]
generally you are going to want to follow this workflow: https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow

**Comment by jeromekelleher** [comment]
Your branch is quite a long way out of date unfortunately @klohmueller. The GitHub [network view](https://github.com/popgensims/manuscript/network) is super helpful in visualising the status of various branches.

**Comment by andrewkern** [comment]
@klohmueller i'm going to close this down so you can wait to pounce on the manuscript

**Pull request closed without merging**
