### PR TITLE
Reworked abstract.

### PR DESCRIPTION
**Pull request by jeromekelleher**
I reworked the abstract a bit. I think we need to be clear on the difference between implementing simulations (i.e., a simulation engine like msprime) and implementing the models. Otherwise readers might be confused that we're proposing a new simulator, or something.

### CODE REVIEW

**Comment by andrewkern** [comment]
so this is a case where I can merge without a rebase right @jeromekelleher? curious in this case as it is a very clean commit, no?

**Comment by jeromekelleher** [comment]
I think you probably can, yeah. We don't really care about keeping a simple history here, so go nuts I'd say.

**Comment by andrewkern** [comment]
okay i'll merge, but out of interest how should i be prioritizing merge vs rebase? the distinction is still a bit blurry in my mind in terms of best practices for maintaining things

**Comment by jeromekelleher** [comment]
Rebasing is nearly always better for bringing personal branches up to date. The only time you want to merge is if there's a long lived development branch that a bunch of people are using (but that's pretty rare). Rebase unless there's a good reason not to, I think.

**Comment by andrewkern** [comment]
okay sgtm

**Comment by jeromekelleher** [comment]
The difference here is we merged in a PR that was behind the tip of master. That's fine here, as noone will ever be doing a git bisect or whatever on this repo, so it makes no difference if the history is linear. It's worth keeping a linear history for bigger/more complicated/longer lived projects though.

**Pull request merged**
